**Luniva Shrestha- 2408028**
(Worksheet - 0)



**4 TO - DO - Task**

**4.1 Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def unit_conversion():
    """
    Converts units of Length, Weight, or Volume.

    User chooses a type of conversion and enters a value.

    Returns:
        float: converted value
    """

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter choice (1-3): "))

        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 3.28084
                print("Result:", result, "ft")
            elif option == 2:
                result = value / 3.28084
                print("Result:", result, "m")

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 2.20462
                print("Result:", result, "lbs")
            elif option == 2:
                result = value / 2.20462
                print("Result:", result, "kg")

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            option = int(input("Choose option: "))

            if option == 1:
                result = value * 0.264172
                print("Result:", result, "gal")
            elif option == 2:
                result = value / 0.264172
                print("Result:", result, "L")

        else:
            print("Invalid conversion type.")

    except ValueError:
        print("Invalid input. Please enter numeric values.")


unit_conversion()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1-3): 1
Enter value to convert: 45
1. Meters to Feet
2. Feet to Meters
Choose option: 1
Result: 147.6378 ft


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [5]:
def find_sum(numbers):
    """Returns the sum of numbers in a list."""
    return sum(numbers)


def find_average(numbers):
    """Returns the average of numbers in a list."""
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """Returns the maximum number in a list."""
    return max(numbers)


def find_min(numbers):
    """Returns the minimum number in a list."""
    return min(numbers)


try:
    nums = input("Enter numbers but separate them by spaces: ")
    numbers = list(map(float, nums.split()))

    if len(numbers) == 0:
        raise ValueError("List cannot be empty.")

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = int(input("Enter choice: "))

    if choice == 1:
        print("Sum =", find_sum(numbers))
    elif choice == 2:
        print("Average =", find_average(numbers))
    elif choice == 3:
        print("Maximum =", find_max(numbers))
    elif choice == 4:
        print("Minimum =", find_min(numbers))
    else:
        print("Invalid choice")

except ValueError:
    print("Invalid input. Please enter numbers.")

Enter numbers but separate them by spaces: 25 25
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 1
Sum = 50.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].
3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].
4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def extract_every_other(lst):
    return lst[::2]


def get_sublist(lst, start, end):
    return lst[start:end+1]


def reverse_list(lst):
    return lst[::-1]


def remove_first_last(lst):
    return lst[1:-1]


def get_first_n(lst, n):
    return lst[:n]


def get_last_n(lst, n):
    return lst[-n:]


def reverse_skip(lst):
    return lst[-2::-2]


In [10]:
lst = [1,2,3,4,5,6]

print(extract_every_other(lst))
print(get_sublist(lst,2,4))
print(reverse_list(lst))
print(remove_first_last(lst))
print(get_first_n(lst,3))
print(get_last_n(lst,2))
print(reverse_skip(lst))

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [12]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): Nested list

    Returns:
    list: Flattened list
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)

    return result


# Example input
nested_list = [[1, 2], [3, 4], [5]]

# Call the function
output = flatten(nested_list)

# Print the result
print("Input:", nested_list)
print("Flattened list:", output)

Input: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [13]:
def access_nested_element(lst, indices):
    """
    Returns an element from a nested list using a list of indices.

    Parameters:
    lst (list): nested list
    indices (list): position of element

    Returns:
    element at given indices
    """
    element = lst
    for i in indices:
        element = element[i]
    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

print("Input List:", lst)
print("Indices:", indices)
print("Output:", access_nested_element(lst, indices))

Input List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Output: 6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [14]:
def sum_nested(lst):
    """
    Returns the sum of all numbers in a nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total


# Example
nested_list = [[1, 2], [3, [4, 5]], 6]

print("Input:", nested_list)
print("Sum:", sum_nested(nested_list))

Input: [[1, 2], [3, [4, 5]], 6]
Sum: 21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [15]:
def remove_element(lst, elem):
    """
    Removes all occurrences of elem from nested list.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)

    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

print("Input:", lst)
print("Element to remove:", elem)
print("Output:", remove_element(lst, elem))

Input: [[1, 2], [3, 2], [4, 5]]
Element to remove: 2
Output: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [16]:
def find_max(lst):
    """
    Returns the maximum value from a nested list.
    """
    maximum = float('-inf')

    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)

    return maximum


# Example
nested_list = [[1, 2], [3, [4, 5]], 6]

print("Input:", nested_list)
print("Maximum:", find_max(nested_list))

Input: [[1, 2], [3, [4, 5]], 6]
Maximum: 6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [17]:
def count_occurrences(lst, elem):
    """
    Counts how many times elem appears in nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

print("Input:", lst)
print("Element to count:", elem)
print("Occurrences:", count_occurrences(lst, elem))

Input: [[1, 2], [2, 3], [2, 4]]
Element to count: 2
Occurrences: 3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [18]:
def deep_flatten(lst):
    """
    Flattens nested lists of any depth.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result


# Example
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

print("Input:", lst)
print("Flattened:", deep_flatten(lst))

Input: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [19]:
def average_nested(lst):
    """
    Calculates average of all elements in nested list.
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


# Example
lst = [[1, 2], [3, 4], [5, 6]]

print("Input:", lst)
print("Average:", average_nested(lst))

Input: [[1, 2], [3, 4], [5, 6]]
Average: 3.5


**10 To - Do - NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [20]:
import numpy as np

# 1. Empty array 2x2
empty_arr = np.empty((2,2))
print("1. Empty Array:\n", empty_arr)

# 2. Ones array 4x2
ones_arr = np.ones((4,2))
print("\n2. Ones Array:\n", ones_arr)

# 3. Array filled with specific value
full_arr = np.full((2,3), 7)
print("\n3. Full Array:\n", full_arr)

# 4. Zeros array with same shape as another array
zeros_like_arr = np.zeros_like(ones_arr)
print("\n4. Zeros Like Array:\n", zeros_like_arr)

# 5. Ones array with same shape as another array
ones_like_arr = np.ones_like(ones_arr)
print("\n5. Ones Like Array:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print("\n6. List converted to Array:", array_from_list)

1. Empty Array:
 [[5.42609005e-315 0.00000000e+000]
 [2.44029516e-312 5.77904633e-317]]

2. Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full Array:
 [[7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Ones Like Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

6. List converted to Array: [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [21]:
import numpy as np

# 1. Array from 10 to 49
arr = np.arange(10,50)
print("1:", arr)

# 2. 3x3 matrix from 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\n2:\n", matrix)

# 3. Identity matrix
identity = np.eye(3)
print("\n3:\n", identity)

# 4. Random array size 30 and mean
rand_arr = np.random.random(30)
print("\n4 Mean:", rand_arr.mean())

# 5. 10x10 random array min and max
rand_matrix = np.random.random((10,10))
print("\n5 Min:", rand_matrix.min())
print("5 Max:", rand_matrix.max())

# 6. Zero array replace 5th element
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6:", zero_arr)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\n7:", arr[::-1])

# 8. Border 1 inside 0
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\n8:\n", border)

# 9. Checkerboard pattern
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\n9:\n", checker)

1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4 Mean: 0.45638252282621405

5 Min: 0.004152463800206729
5 Max: 0.9887219101823751

6: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7: [0 4 0 0 2 1]

8:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [22]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Add
print("Add:\n", x + y)

# 2 Subtract
print("\nSubtract:\n", x - y)

# 3 Multiply by integer
print("\nMultiply by 3:\n", x * 3)

# 4 Square
print("\nSquare:\n", np.square(x))

# 5 Dot products
print("\nDot v.w:", np.dot(v,w))
print("Dot x.v:", np.dot(x,v))
print("Dot x.y:\n", np.dot(x,y))

# 6 Concatenate
print("\nConcat x,y rows:\n", np.vstack((x,y)))
print("\nConcat v,w columns:\n", np.column_stack((v,w)))

# 7 Concatenate x and v
try:
    print(np.vstack((x,v)))
except Exception as e:
    print("\nError:", e)

Add:
 [[ 6  8]
 [10 13]]

Subtract:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot v.w: 219
Dot x.v: [29 77]
Dot x.y:
 [[19 22]
 [50 58]]

Concat x,y rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concat v,w columns:
 [[ 9 11]
 [10 12]]
[[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT.

In [23]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1 Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1:\n", np.dot(A,A_inv))

# 2 Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)

# 3 Prove (AB)^T = B^T A^T
left = (AB).T
right = np.dot(B.T, A.T)

print("\n(AB)^T:\n", left)
print("\nB^T A^T:\n", right)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [25]:
import numpy as np

A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Solve
X = np.linalg.inv(A).dot(B)

print("Solution [x,y,z]:", X)

Solution [x,y,z]: [ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

In [27]:
import numpy as np
import time

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [28]:
# using python lists
size = 1000000

a = list(range(size))
b = list(range(size))

start = time.time()

result = [a[i] + b[i] for i in range(size)]

end = time.time()

print("Python List Addition Time:", end - start)

Python List Addition Time: 0.12128925323486328


In [29]:
# using NumPy arrays
a_np = np.array(a)
b_np = np.array(b)

start = time.time()

result_np = a_np + b_np

end = time.time()

print("NumPy Addition Time:", end - start)

NumPy Addition Time: 0.0037953853607177734


2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [30]:
# Using Python Lists
start = time.time()

result = [a[i] * b[i] for i in range(size)]

end = time.time()

print("Python List Multiplication Time:", end - start)

Python List Multiplication Time: 0.12935495376586914


In [31]:
# Using NumPy
start = time.time()

result_np = a_np * b_np

end = time.time()

print("NumPy Multiplication Time:", end - start)

NumPy Multiplication Time: 0.0055446624755859375


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [32]:
# Using Python Lists
start = time.time()

dot = sum(a[i] * b[i] for i in range(size))

end = time.time()

print("Python Dot Product Time:", end - start)

Python Dot Product Time: 0.10942959785461426


In [33]:
# Using NumPy
start = time.time()

dot_np = np.dot(a_np, b_np)

end = time.time()

print("NumPy Dot Product Time:", end - start)

NumPy Dot Product Time: 0.0035257339477539062


4. Matrix Multiplication

  • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

  • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.Measure and print the time taken for this operation.

In [34]:
# Using Python Lists
size = 1000

A = [[i for i in range(size)] for j in range(size)]
B = [[i for i in range(size)] for j in range(size)]

start = time.time()

result = [[sum(A[i][k] * B[k][j] for k in range(size)) for j in range(size)] for i in range(size)]

end = time.time()

print("Python Matrix Multiplication Time:", end - start)

Python Matrix Multiplication Time: 195.76883006095886


In [35]:
# Using NumPy
A_np = np.random.rand(1000,1000)
B_np = np.random.rand(1000,1000)

start = time.time()

C = np.dot(A_np, B_np)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.07589197158813477
